#!/bin/busybox sh

get_value() {
  var=$1
  shift
  field=$1
  shift
  line=$@
  value=
  if [ -z "${line##$field=*}" ];then
    value=`echo $line|sed -e s/$field=//`
  fi
  if [ ! -z $value ];then
    eval $var=$value
  fi
}

PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH

/bin/busybox mkdir -p /usr
/bin/busybox ln -s /bin /usr/bin
/bin/busybox ln -s /sbin /usr/sbin
/bin/busybox --install -s

mkdir -p /dev /mnt /proc /sys /run /dev/pts

if ! mount -t devtmpfs -o size=10M,mode=0755 udev /dev; then
    echo "W: devtmpfs not available, falling back to tmpfs for /dev"
    mount -t tmpfs -o size=10M,mode=0755 udev /dev
    [ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
    [ -e /dev/null ] || mknod /dev/null c 1 3
fi

mount -t proc proc /proc
mount -t sysfs sysfs /sys

mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
mount -t tmpfs -o "nosuid,size=20%,mode=0755" tmpfs /run
mkdir -m 0755 /run/initramfs

for i in `cat /proc/cmdline`;do
  get_value root_param root $i
  get_value init_param init $i
done

hostname blankon

. /etc/blankon/init

ENV=/etc/blankon/shinit
export ENV

uname -a

if [ -z $root_param ];then
  /bin/busybox sh
  exit
fi

if [ -z $init_param ];then
  init_param=/sbin/init
fi

mount -o rw $root_param /mnt
mount -n -o move /dev /mnt/dev
mount -n -o move /run /mnt/run
mount -n -o move /sys /mnt/sys
mount -n -o move /proc /mnt/proc

echo $root_param : $init_param
exec switch_root /mnt $init_param "$@" </mnt/dev/console >/mnt/dev/console
